# Generated by Django 4.2.7 on 2025-08-19 10:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کتاب')),
                ('author', models.CharField(max_length=200, verbose_name='نویسنده')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cover_image', models.ImageField(upload_to='book_covers/', verbose_name='تصویر جلد')),
                ('reading_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز خواندن')),
                ('quiz_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز آزمون')),
                ('reading_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد روزهای خواندن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['stage__order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دوره')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دوره کتابخوانی',
                'verbose_name_plural': 'دوره\u200cهای کتابخوانی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(choices=[(1, 'مرحله اول'), (2, 'مرحله دوم'), (3, 'مرحله سوم')], verbose_name='شماره مرحله')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('order', models.IntegerField(verbose_name='ترتیب')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='books.readingperiod', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'مرحله',
                'verbose_name_plural': 'مراحل',
                'ordering': ['order'],
                'unique_together': {('period', 'stage_number')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, verbose_name='امتیاز کل')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.stage', verbose_name='مرحله فعلی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضا',
            },
        ),
        migrations.CreateModel(
            name='BookAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تخصیص')),
                ('due_date', models.DateTimeField(verbose_name='تاریخ موعد')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بازگشت')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('reading_score_earned', models.IntegerField(default=0, verbose_name='امتیاز خواندن کسب شده')),
                ('quiz_score_earned', models.IntegerField(default=0, verbose_name='امتیاز آزمون کسب شده')),
                ('late_days', models.IntegerField(default=0, verbose_name='روزهای تاخیر')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='books.book', verbose_name='کتاب')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_assignments', to='books.member', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'تخصیص کتاب',
                'verbose_name_plural': 'تخصیص\u200cهای کتاب',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.stage', verbose_name='مرحله'),
        ),
    ]
