# Generated by Django 4.2.7 on 2025-08-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        # حذف فیلدهای قدیمی
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='joined_at',
        ),
        
        # اضافه کردن فیلدهای جدید
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # تغییر فیلدهای Book
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='تصویر جلد'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reading_score',
            field=models.IntegerField(default=0, verbose_name='امتیاز مطالعه'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quiz_score',
            field=models.IntegerField(default=0, verbose_name='امتیاز آزمون'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reading_days',
            field=models.IntegerField(default=3, verbose_name='تعداد روز مطالعه'),
        ),
        
        # تغییر فیلدهای Stage
        migrations.AlterField(
            model_name='stage',
            name='stage_number',
            field=models.IntegerField(verbose_name='شماره مرحله'),
        ),
        migrations.AddField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        
        # تغییر فیلدهای BookAssignment
        migrations.AddField(
            model_name='bookassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت‌ها'),
        ),
        
        # تغییر نام فیلدها
        migrations.RenameField(
            model_name='bookassignment',
            old_name='reading_score_earned',
            new_name='reading_score_earned',
        ),
    ]
