# Generated by Django 4.2.7 on 2025-08-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20250819_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-total_score', 'first_name'], 'verbose_name': 'عضو', 'verbose_name_plural': 'اعضا'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order', 'stage_number'], 'verbose_name': 'مرحله', 'verbose_name_plural': 'مراحل'},
        ),
        migrations.AlterField(
            model_name='book',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.stage', verbose_name='مرحله'),
        ),
        migrations.AlterField(
            model_name='bookassignment',
            name='assigned_date',
            field=models.DateTimeField(verbose_name='تاریخ تخصیص'),
        ),
        migrations.AlterField(
            model_name='bookassignment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='bookassignment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.member', verbose_name='عضو'),
        ),
        migrations.AlterField(
            model_name='bookassignment',
            name='reading_score_earned',
            field=models.IntegerField(default=0, verbose_name='امتیاز مطالعه کسب شده'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.readingperiod', verbose_name='دوره'),
        ),
    ]
