# Generated by Django 5.2.7 on 2025-10-24 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_member_options_alter_stage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookassignment',
            options={'ordering': ['-assigned_date'], 'verbose_name': 'امانت گرفتن کتاب', 'verbose_name_plural': 'امانت\u200cهای کتاب'},
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='bookassignment',
            name='assigned_date',
            field=models.DateTimeField(verbose_name='تاریخ امانت گرفتن'),
        ),
    ]
