# Generated by Django 5.2.7 on 2025-10-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookassignment_options_member_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stages/images/', verbose_name='تصویر مرحله'),
        ),
    ]
