# Generated by Django 5.2.7 on 2025-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_stage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.CharField(choices=[('soleimani', 'گروه شهید سلیمانی'), ('fakhrizadeh', 'گروه شهید فخری زاده')], default='soleimani', max_length=20, verbose_name='گروه'),
        ),
    ]
