# Generated by Django 5.2.7 on 2025-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_member_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='members/profiles/', verbose_name='تصویر پروفایل'),
        ),
    ]
