# Generated by Django 5.2.7 on 2025-10-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_member_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='تاریخ شروع هفته')),
                ('week_end_date', models.DateField(verbose_name='تاریخ پایان هفته')),
                ('weekly_score', models.IntegerField(default=0, verbose_name='امتیاز هفتگی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='books.member', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'امتیاز هفتگی',
                'verbose_name_plural': 'امتیازات هفتگی',
                'ordering': ['-weekly_score', '-week_start_date'],
                'unique_together': {('member', 'week_start_date')},
            },
        ),
    ]
