# Generated by Django 4.2.7 on 2025-11-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_weeklyscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد صفحات'),
        ),
    ]
