# Generated by Django 4.2.7 on 2025-11-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_bookassignment_pages_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookassignment',
            name='quiz_score_base',
            field=models.IntegerField(default=0, verbose_name='امتیاز آزمون پایه'),
        ),
        migrations.AddField(
            model_name='bookassignment',
            name='reading_score_base',
            field=models.IntegerField(default=0, verbose_name='امتیاز مطالعه پایه'),
        ),
    ]
