# Generated by Django 4.2.7 on 2025-08-19 10:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookHandout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handed_out_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تحویل')),
                ('due_date', models.DateTimeField(verbose_name='تاریخ موعد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='کتاب')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.member', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'تحویل کتاب',
                'verbose_name_plural': 'تحویل\u200cهای کتاب',
                'ordering': ['-handed_out_date'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آزمون')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('max_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='حداکثر امتیاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='متن سوال')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'چند گزینه\u200cای'), ('true_false', 'درست/غلط'), ('short_answer', 'پاسخ کوتاه')], max_length=20, verbose_name='نوع سوال')),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='امتیاز')),
                ('order', models.IntegerField(verbose_name='ترتیب')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading_sessions.quiz', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'سوال آزمون',
                'verbose_name_plural': 'سوالات آزمون',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='reading_sessions.quizquestion', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه سوال',
                'verbose_name_plural': 'گزینه\u200cهای سوال',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز کسب شده')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.member', verbose_name='عضو')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading_sessions.quiz', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'تلاش آزمون',
                'verbose_name_plural': 'تلاش\u200cهای آزمون',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازگشت')),
                ('quiz_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز آزمون')),
                ('late_days', models.IntegerField(default=0, verbose_name='روزهای تاخیر')),
                ('final_reading_score', models.IntegerField(default=0, verbose_name='امتیاز نهایی خواندن')),
                ('total_score', models.IntegerField(default=0, verbose_name='امتیاز کل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('handout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reading_sessions.bookhandout', verbose_name='تحویل')),
            ],
            options={
                'verbose_name': 'بازگشت کتاب',
                'verbose_name_plural': 'بازگشت\u200cهای کتاب',
                'ordering': ['-returned_date'],
            },
        ),
    ]
