# Generated by Django 4.2.7 on 2025-08-19 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تلفن')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل عضو',
                'verbose_name_plural': 'پروفایل\u200cهای اعضا',
            },
        ),
    ]
