# Generated by Django 4.2.7 on 2025-11-07 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_usersessionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('duration_seconds', models.PositiveBigIntegerField(default=0, verbose_name='مدت حضور در روز (ثانیه)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حضور روزانه کاربر',
                'verbose_name_plural': 'حضور روزانه کاربران',
                'ordering': ['-date', '-updated_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
